### PR TITLE
checked and verified messages tagged with 'gettext'.

### PR DESCRIPTION
**Pull request by triantares**

### CODE REVIEW

**Review by Thanatermesis — APPROVED** [review]
I'm curious, these messages are (should be) available on eltrans, why not doing them directly on eltrans? :)

**Comment by triantares** [comment]
Not through 'eltrans', I would like to but cannot.
I can only access >90% approved apps. all the others fail. That includes some I've already done. :(
image

image

**Comment by triantares** [comment]
Like I mentioned on the forum:
Give me full access and I'll have the whole shebang corrected in a few hours time.

**Comment by Thanatermesis** [comment]
Oh  I see!

Mmh... now im a bit confused, seems like (almost) all of them shows up as "requires approvals" (so you cannot edit anyone except 3 of them?), If I'm not wrong, before there was around half of them editable

This makes me think that after somebody (you on this case) improved the english, these improvements shows up as they requires to be approved...

is this what is happening?

example: in the case of "desktop health wrapper" (7 messages):

image

the first messages (with empty translation in the right side) are the ones that requires approvals, is these the messages you previously improved?

**Comment by triantares** [comment]
Yes, exactly.
The ones where I altered the text were inaccessible after I altered and submitted them.
The programs (at least most of them) are so small that any alteration brings them down below 90%. :(

I cannot even open elive-skel, let alone edit it.
I think you need to fill the empty spaces ..... even if it's gibberish to get to 90%

**Comment by Thanatermesis** [comment]
> Yes, exactly.

I see, mmh... well I think this is technically correct (a need of verification for the original messages) but is also a bit annoying, it is in any case not so needed **at the moment** (so future people that would replace the original sentences should be always verified)

> I think you need to fill the empty spaces ..... even if it's gibberish to get to 90%

not sure to understand what you mean, for example "applications-compatibility" has only 2 messages, if only one is modified, the percent becomes 50% :) 

In any case let's do some betatesting to see how this workflow is going, let's do some tests with "elive desktop wrapper" now (only 7 sentences, easy / fast to test, then we will see what to do with the other ones)

**Comment by Thanatermesis** [comment]
Ok I did some test, so basically this is what happened (elive-desktop-wrapper translations):

* there was only a 28% of the messages approved, so i opened eltrans and approved them: https://dev.elivecd.org/changeset/5626 
* but there was 3 which I have rewrote, at first eltrans directly showed "all 100% completed" but after to repackage, since there was 3 new sentences (modified == new sentences), eltrans showed them later as not completed https://dev.elivecd.org/changeset/5627
* so i opened again eltrans, and just approved these 3 new sentences (since i know is the ones that I have previously assigned i know they are good now)
* eltrans shows now as "100% completed" for "elive-desktop-wrapper" (you can still improve these sentences if you think they are wrong, but they shows as correctly completed now

_timeline:_

image

**Comment by Thanatermesis** [comment]
now im trying to think how we should manage with the other ones... which ones are the ones that you **don't** have improved yet? (now the list shows that more needs approvals, but which ones are originally the ones that you were not yet able to edit?) @triantares

**Pull request merged**
